#!/bin/bash
# Project Pulse Backend - Quick Commands Reference

echo "🚀 Project Pulse Backend - Quick Commands"
echo "=========================================="
echo ""
echo "📦 Development"
echo "  npm run dev              - Start development server with auto-reload"
echo "  npm run build            - Build TypeScript to JavaScript"
echo "  npm start                - Start production server (after build)"
echo "  npm run type-check       - Run TypeScript type checking"
echo ""
echo "🗄️  Database (Prisma)"
echo "  npm run prisma:generate  - Generate Prisma Client"
echo "  npm run prisma:migrate  - Create and apply migration"
echo "  npm run prisma:push     - Push schema to DB (no migration)"
echo "  npm run prisma:studio   - Open Prisma Studio (DB GUI)"
echo ""
echo "📁 Project Structure"
echo "  src/config/             - Configuration files"
echo "  src/modules/            - Feature modules (10 modules)"
echo "  src/middlewares/        - Express middlewares"
echo "  src/utils/              - Utility functions"
echo "  prisma/                 - Prisma schema and migrations"
echo "  logs/                   - Application logs"
echo "  uploads/                - File uploads"
echo ""
echo "🔧 Environment Setup"
echo "  1. cp .env.example .env"
echo "  2. Edit .env with your database credentials"
echo "  3. Create PostgreSQL database"
echo "  4. npm run prisma:migrate"
echo "  5. npm run dev"
echo ""
echo "🌐 Endpoints"
echo "  GET /health             - Health check"
echo "  (More endpoints will be added in future phases)"
echo ""
